[package]
name = "naiagame-client"
version = "0.1.0"
edition = "2018"

[dependencies]
kiss3d = "0.31.0"
log = "0.4.14"
naia-client = "0.5.0"
naiagame-shared = { path = "../shared" }
simplelog = "0.10.0"
