[package]
name = "naiagame-server"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
simple_logger = "1.11.0"
smol = "1.2.5"
naia-server = { version = "0.5.0" }
naiagame-shared = { path = "../shared" }

[features]
default = [ "use-udp" ]
use-udp = [ "naia-server/use-udp" ]
