[package]
name = "naiagame-server"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
smol = "1.2.5"
naia-server = { version = "0.5.0" }
naiagame-shared = { path = "../shared" }
simplelog = "0.10.0"

[features]
default = [ "use-udp" ]
use-udp = [ "naia-server/use-udp" ]
